// Generated from Static Runtime IR. Run npm run runtime:contracts to regenerate.
import type { LlvmModuleBuilder } from "../../llvm-ir/index.js";
import { arraysContracts } from "../arrays.js";
import { type RuntimeCalleeTable, registerRuntimeContract } from "../register.js";

export function createArraysCallees(module: LlvmModuleBuilder): RuntimeCalleeTable<typeof arraysContracts> {
  return {
    "valueArrayPtr": registerRuntimeContract(module, arraysContracts.valueArrayPtr),
    "arrayValidateMapper": registerRuntimeContract(module, arraysContracts.arrayValidateMapper),
    "arrayFromCollection": registerRuntimeContract(module, arraysContracts.arrayFromCollection),
    "arrayFromIteratorMapped": registerRuntimeContract(module, arraysContracts.arrayFromIteratorMapped),
    "arrayFromValue": registerRuntimeContract(module, arraysContracts.arrayFromValue),
    "valueArrayGet": registerRuntimeContract(module, arraysContracts.valueArrayGet),
    "valueArrayLength": registerRuntimeContract(module, arraysContracts.valueArrayLength),
    "valueArraySet": registerRuntimeContract(module, arraysContracts.valueArraySet),
    "valueArraySetLength": registerRuntimeContract(module, arraysContracts.valueArraySetLength),
    "valueArrayDelete": registerRuntimeContract(module, arraysContracts.valueArrayDelete),
    "arrayNew": registerRuntimeContract(module, arraysContracts.arrayNew),
    "arrayFromFixed": registerRuntimeContract(module, arraysContracts.arrayFromFixed),
    "arrayLength": registerRuntimeContract(module, arraysContracts.arrayLength),
    "arrayGet": registerRuntimeContract(module, arraysContracts.arrayGet),
    "arrayGetWithKey": registerRuntimeContract(module, arraysContracts.arrayGetWithKey),
    "arraySetNamed": registerRuntimeContract(module, arraysContracts.arraySetNamed),
    "arrayDeleteNamed": registerRuntimeContract(module, arraysContracts.arrayDeleteNamed),
    "arrayHasOwnIndex": registerRuntimeContract(module, arraysContracts.arrayHasOwnIndex),
    "arraySet": registerRuntimeContract(module, arraysContracts.arraySet),
    "arrayDelete": registerRuntimeContract(module, arraysContracts.arrayDelete),
    "arraySetLength": registerRuntimeContract(module, arraysContracts.arraySetLength),
    "arrayHas": registerRuntimeContract(module, arraysContracts.arrayHas),
    "arrayKeys": registerRuntimeContract(module, arraysContracts.arrayKeys),
    "arrayValues": registerRuntimeContract(module, arraysContracts.arrayValues),
    "arrayEntries": registerRuntimeContract(module, arraysContracts.arrayEntries),
    "arrayOwnPropertyDescriptor": registerRuntimeContract(module, arraysContracts.arrayOwnPropertyDescriptor),
    "arrayLengthPropertyDescriptor": registerRuntimeContract(module, arraysContracts.arrayLengthPropertyDescriptor),
    "arrayOwnPropertyDescriptors": registerRuntimeContract(module, arraysContracts.arrayOwnPropertyDescriptors),
    "arrayIncludes": registerRuntimeContract(module, arraysContracts.arrayIncludes),
    "arrayIndexOf": registerRuntimeContract(module, arraysContracts.arrayIndexOf),
    "arrayLastIndexOf": registerRuntimeContract(module, arraysContracts.arrayLastIndexOf),
    "arrayFind": registerRuntimeContract(module, arraysContracts.arrayFind),
    "arrayFindIndex": registerRuntimeContract(module, arraysContracts.arrayFindIndex),
    "arrayAt": registerRuntimeContract(module, arraysContracts.arrayAt),
    "arrayCopyWithin": registerRuntimeContract(module, arraysContracts.arrayCopyWithin),
    "arraySlice": registerRuntimeContract(module, arraysContracts.arraySlice),
    "arraySplice": registerRuntimeContract(module, arraysContracts.arraySplice),
    "arrayFlat": registerRuntimeContract(module, arraysContracts.arrayFlat),
    "arrayConcat": registerRuntimeContract(module, arraysContracts.arrayConcat),
    "arrayFill": registerRuntimeContract(module, arraysContracts.arrayFill),
    "arrayReverse": registerRuntimeContract(module, arraysContracts.arrayReverse),
    "arrayFromArray": registerRuntimeContract(module, arraysContracts.arrayFromArray),
    "arrayFromArgv": registerRuntimeContract(module, arraysContracts.arrayFromArgv),
    "arrayFromObject": registerRuntimeContract(module, arraysContracts.arrayFromObject),
    "arraySortDefault": registerRuntimeContract(module, arraysContracts.arraySortDefault),
    "arrayJoin": registerRuntimeContract(module, arraysContracts.arrayJoin),
    "arrayPush": registerRuntimeContract(module, arraysContracts.arrayPush),
    "arrayPop": registerRuntimeContract(module, arraysContracts.arrayPop),
    "arrayUnshift": registerRuntimeContract(module, arraysContracts.arrayUnshift),
    "arrayShift": registerRuntimeContract(module, arraysContracts.arrayShift),
    "arraySetPrototype": registerRuntimeContract(module, arraysContracts.arraySetPrototype),
    "arrayGetPrototype": registerRuntimeContract(module, arraysContracts.arrayGetPrototype),
    "arrayOwnPropertyNames": registerRuntimeContract(module, arraysContracts.arrayOwnPropertyNames),
    "arrayAppendElements": registerRuntimeContract(module, arraysContracts.arrayAppendElements),
  };
}
