; External symbol declarations for the runtime.
declare ptr @malloc(i64)
declare ptr @memcpy(ptr, ptr, i64)
declare i32 @memcmp(ptr, ptr, i64)
declare i32 @sprintf(ptr, ptr, ...)
declare ptr @getenv(ptr)
declare i64 @strtol(ptr, ptr, i32)
declare void @free(ptr)
declare double @llvm.fabs.f64(double)
declare double @llvm.floor.f64(double)
declare double @llvm.ceil.f64(double)
declare double @llvm.trunc.f64(double)
declare double @llvm.round.f64(double)
declare double @llvm.sqrt.f64(double)
declare double @llvm.pow.f64(double, double)
declare double @llvm.exp.f64(double)
declare double @llvm.log.f64(double)
declare double @llvm.log2.f64(double)
declare double @llvm.log10.f64(double)
declare double @llvm.sin.f64(double)
declare double @llvm.cos.f64(double)
declare i32 @llvm.ctlz.i32(i32, i1)
declare double @strtod(ptr, ptr)
declare i64 @strlen(ptr)
