import { describe, test } from "vitest";
import { roadmapIntegrationTimeoutMs } from "./helpers.js";
import { expectNativeMatchesNodeIfAvailable } from "./oracle.js";

const oracleFixtures = [
  "hello.ts",
  "multiple-prints.ts",
  "while-loop.ts",
  "const-number-addition.ts",
  "boolean-coercion-supported-values.ts",
  "function-call.ts",
  "nested-function-declaration.ts",
  "nested-function-in-try.ts",
  "function-value-variable-call.ts",
  "function-value-arrow-call.ts",
  "function-value-argument-call.ts",
  "function-value-property-call.ts",
  "function-value-string-closure.ts",
  "function-value-independent-closures.ts",
  "function-value-method-this.ts",
  "function-value-identity.ts",
  "function-constructor-object-return.ts",
  "catch-destructure-default-throws.ts",
  "catch-destructure-default-lazy.ts",
  "catch-destructure-object-default.ts",
  "gc-catch-destructure-default.ts",
  "array-runtime-push-pop.ts",
  "object-runtime-dynamic-store.ts",
  "map-basic-set-get.ts",
  "set-basic-add-has.ts",
  "string-runtime-trim-methods.ts",
  "math-basic-number-functions.ts",
  "number-coercion-primitives.ts",
  "json-parse-primitives.ts",
  "destructure-nested.ts",
  "destructure-builtin-iterables.ts",
  "destructure-iterator-protocol.ts",
  "destructure-iterator-override.ts",
  "destructure-non-iterable.ts",
  "array-runtime-map-thisarg.ts",
  "array-runtime-callback-thisarg-methods.ts",
  "array-runtime-arrow-thisarg-evaluation.ts",
  "array-runtime-reduce-initial-not-thisarg.ts",
  "array-runtime-reduce-right-initial-not-thisarg.ts",
  "array-runtime-thisarg-strict-values.ts",
  "array-runtime-map-thisarg-in-function.ts",
  "array-runtime-property-thisarg.ts",
  "array-runtime-arrow-lexical-this.ts",
  "class-basic-method.ts",
  "gc-retain-live.ts",
  "throw-string-top-level.ts",
  "throw-across-function-caught.ts",
  "throw-across-function-value.ts",
  "throw-across-array-callback.ts",
  "throw-nested-rethrow.ts",
  "gc-retain-thrown-value.ts",
  "for-of-user-iterator.ts",
  "for-of-iterator-assigned.ts",
  "for-of-class-iterator.ts",
  "for-of-iterator-nested-break.ts",
  "for-of-iterator-caught-throw.ts",
  "for-of-iterator-missing.ts",
  "for-of-iterator-non-callable.ts",
  "for-of-iterator-method-primitive.ts",
  "for-of-iterator-next-non-callable.ts",
  "for-of-iterator-result-primitive.ts",
  "for-of-iterator-throws.ts",
  "for-of-iterator-next-throws.ts",
  "try-finally-basic.ts",
  "try-catch-finally.ts",
  "try-finally-return.ts",
  "try-finally-throw.ts",
  "try-finally-nested.ts",
  "try-finally-nested-pending.ts",
  "try-finally-precedence.ts",
  "try-finally-break-continue.ts",
  "for-of-iterator-break-close.ts",
  "for-of-iterator-return-close.ts",
  "for-of-iterator-throw-close.ts",
  "for-of-iterator-continue-no-close.ts",
  "for-of-iterator-close-order.ts",
  "for-of-iterator-return-throws.ts",
  "for-of-iterator-return-non-callable.ts",
  "for-of-iterator-close-semantics.ts",
  "for-of-iterator-propagated-throw.ts",
  "gc-try-finally-return.ts",
  "gc-cleanup-pending-values.ts"
] as const;

describe("Node correctness oracle", () => {
  test.each(oracleFixtures)("matches Node for %s", async (fixture) => {
    await expectNativeMatchesNodeIfAvailable(fixture);
  }, roadmapIntegrationTimeoutMs);
});
